CREATE TABLE [dbo].[ProductsRun](
[ProductID][int]IDENTITY(1,1) NOT NULL,
[Name][nvarchar] (max) NULL,
[Quantity][int] NULL,
[Price][float]NULL,
CONSTRAINT [PK_Products]PRIMARY KEY CLUSTERED (
[ProductId]ASC
)WITH (PAD_INDEX=OFF,STATISTICS_NORECOMPUTE=OFF,IGNORE_DUP_KEY=OFF,IGNORE_DUP_KEY=OFF,ALLOW_ROW_LOCKS=ON,ALLOW_PAGE_LOCKS=ON)ON[PRIMARY]
)ON [PRIMARY] TEXTIMAGE_ON[PRIMARY]
GO